FROM ubuntu:noble
RUN apt -y update && apt install -y git cmake g++
RUN apt -y update && apt install -y qml6-module-qt-labs-settings qml6-module-qtquick-dialogs qml6-module-qtquick-templates qml6-module-qtquick-window qml6-module-qtqml qt6-base-dev qt6-declarative-dev libglu1-mesa-dev

